from PIL import Image, ImageDraw, ImageFont
import os

DEFAULT_FONT_PATH = "./fonts/GOTHAM-BOLD.TTF"
STANDINGSAPIBASEURL = "https://api.simulationsoccer.com/index/standings"
NA_PLACEHOLDER = "N/A"
LEAGUEIDMAPPING = {
    "major": 1,
    "minor": 2,
    "ssl cup": 0,
    "ssl shield": 0,  
}
MAJOR_LEAGUE_TEAMS_LIST = [
    "CA Buenos Aires", "Tokyo S.C.", "Hollywood FC", "CF Catalunya", "A.C. Romana",
    "União São Paulo", "Reykjavik United", "Schwarzwälder FV", "Shanghai Dragons FC", "CD Tenochtitlan", "Xelajú Cósmico FC", "Liffeyside Celtic FC"
]

MINOR_LEAGUE_TEAMS_LIST = [
    "AS Paris", "Montréal United", "Rapid Magyar SC", "Inter London", "Krung Thep FC",
    "North Shore United", "Athênai F.C.", "Cairo City", "Seoul MFC", "F.C. Kaapstad", "AF Masques Sacrés", "CS Rova Mpanjaka"
]
ALL_MAIN_TOURNAMENT_TEAMS = MAJOR_LEAGUE_TEAMS_LIST + MINOR_LEAGUE_TEAMS_LIST

ACADEMY_TEAMS = []

TEAM_ABBREVIATIONS = {
    "usp": "União São Paulo", "sao paulo": "União São Paulo", "asp": "AS Paris", "paris": "AS Paris",
    "asparis": "AS Paris", "cdt": "CD Tenochtitlan", "acr": "A.C. Romana", "sfv": "Schwarzwälder FV",
    "reyk": "Reykjavik United", "cata": "CF Catalunya", "hol": "Hollywood FC", "tok": "Tokyo S.C.",
    "sha": "Shanghai Dragons FC", "caba": "CA Buenos Aires", "mont": "Montréal United",
    "magyar": "Rapid Magyar SC", "london": "Inter London", "ktp": "Krung Thep FC",
    "nsu": "North Shore United", "athenai": "Athênai F.C.", "cairo": "Cairo City",
    "seoul": "Seoul MFC", "kaapstad": "F.C. Kaapstad", "ath": "Athênai F.C.", "cai": "Cairo City",
    "hol": "Hollywood FC", "lon": "Inter London", "tok": "Tokyo S.C.", "mtl": "Montréal United",
    "cat": "CF Catalunya", "seo": "Seoul MFC", "par": "AS Paris", "fck": "F.C. Kaapstad",
    "rkv": "Reykjavik United", "sfv": "Schwarzwälder FV", "nsu": "North Shore United",
    "sha": "Shanghai Dragons FC", "mag": "Rapid Magyar SC", "kth": "Krung Thep FC",
    "buenos aires": "CA Buenos Aires", "tokyo": "Tokyo S.C.", "hollywood": "Hollywood FC",
    "hfc": "Hollywood FC", "catalunya": "CF Catalunya", "romana": "A.C. Romana",
    "roma": "A.C. Romana", "uniao": "União São Paulo", "reykjavik": "Reykjavik United",
    "schwarzwalder": "Schwarzwälder FV", "black forest": "Schwarzwälder FV",
    "shanghai": "Shanghai Dragons FC", "tenochtitlan": "CD Tenochtitlan", "paris": "AS Paris",
    "montreal": "Montréal United", "mon": "Montréal United", "rapid magyar": "Rapid Magyar SC",
    "london": "Inter London", "inter": "Inter London", "krung thep": "Krung Thep FC",
    "north shore": "North Shore United", "athenai": "Athênai F.C.", "cairo": "Cairo City",
    "seoul": "Seoul MFC", "kaapstad": "F.C. Kaapstad", "xelaju": "Xelajú Cósmico FC",
    "afmsd" : "AF Masques Sacrés", "liffeyside": "Liffeyside Celtic FC", "csrm": "CS Rova Mpanjaka",
    "xcfc": "Xelajú Cósmico FC", "lcfc": "Liffeyside Celtic FC", "xlc": "Xelajú Cósmico FC",
    "msd" : "AF Masques Sacrés", "lif": "Liffeyside Celtic FC", "rmp": "CS Rova Mpanjaka", "rova": "CS Rova Mpanjaka"
}

CURRENT_SEASON = "23"

DEFAULT_LOGO_PATH = "./graphics/logos/league-logo.png"  
MAJOR_LEAGUE_LOGO_PATH = "./graphics/logos/major_league_logo.png"
MINOR_LEAGUE_LOGO_PATH = "./graphics/logos/minor_league_logo.png"
MAJORS_DIV1_LOGO_PATH = "./graphics/logos/majors_div1.png"
MAJORS_DIV2_LOGO_PATH = "./graphics/logos/majors_div2.png"
MINORS_DIV1_LOGO_PATH = "./graphics/logos/minors_div1.png"
MINORS_DIV2_LOGO_PATH = "./graphics/logos/minors_div2.png"

def get_team_logo_path(team_name): # Returns the file path for the team logo image based on the team name.
    
    team_key = team_name.lower()
    imagename = team_key.replace(' ', '_')

    if team_key in{t.lower() for t in ALL_MAIN_TOURNAMENT_TEAMS}:
        team_logo_path = f"graphics/logos/{imagename}.png"
    
    elif team_key in{t.lower() for t in ACADEMY_TEAMS}:
        team_logo_path = f"graphics/logos/academy_{imagename}.png"    
    
    if os.path.isfile(team_logo_path): # If the file does not exist, returns the default logo path.
        return team_logo_path
    else:
        return DEFAULT_LOGO_PATH

MAJOR_TROPHY_PATH= "./graphics/trophies/SSL_Major_Trophy_Front.png"
MINOR_TROPHY_PATH= "./graphics/trophies/SSL_Minor_Trophy_Front.png"


DEMO_STANDINGS_DATA = [
    {
        "team": "AS Paris",
        "season": 22,
        "matchtype": 2,
        "matchday": "1",
        "mp": 22,
        "w": 20,
        "d": 1,
        "l": 1,
        "gf": 85,
        "ga": 11,
        "gd": 74,
        "p": 61,
    },
    {
        "team": "União São Paulo",
        "season": 22,
        "matchtype": 1,
        "matchday": "1",
        "mp": 22,
        "w": 18,
        "d": 3,
        "l": 1,
        "gf": 83,
        "ga": 25,
        "gd": 58,
        "p": 57,
    },
    {
        "team": "Hollywood FC",
        "season": 22,
        "matchtype": 1,
        "matchday": "1",
        "mp": 22,
        "w": 17,
        "d": 1,
        "l": 4,
        "gf": 73,
        "ga": 32,
        "gd": 41,
        "p": 52,
    },
    {
        "team": "F.C. Kaapstad",
        "season": 22,
        "matchtype": 2,
        "matchday": "1",
        "mp": 22,
        "w": 16,
        "d": 2,
        "l": 4,
        "gf": 80,
        "ga": 28,
        "gd": 52,
        "p": 50,
    },
    {
        "team": "Reykjavik United",
        "season": 22,
        "matchtype": 1,
        "matchday": "1",
        "mp": 22,
        "w": 16,
        "d": 2,
        "l": 4,
        "gf": 68,
        "ga": 30,
        "gd": 38,
        "p": 50,
    },
    {
        "team": "Seoul MFC",
        "season": 22,
        "matchtype": 2,
        "matchday": "1",
        "mp": 22,
        "w": 15,
        "d": 2,
        "l": 5,
        "gf": 64,
        "ga": 30,
        "gd": 34,
        "p": 47,
    },
    {
        "team": "Schwarzwälder FV",
        "season": 22,
        "matchtype": 1,
        "matchday": "1",
        "mp": 22,
        "w": 14,
        "d": 1,
        "l": 7,
        "gf": 59,
        "ga": 41,
        "gd": 18,
        "p": 43,
    },
    {
        "team": "Montréal United",
        "season": 22,
        "matchtype": 2,
        "matchday": "1",
        "mp": 22,
        "w": 13,
        "d": 3,
        "l": 6,
        "gf": 69,
        "ga": 45,
        "gd": 24,
        "p": 42,
    },
    {
        "team": "Rapid Magyar SC",
        "season": 22,
        "matchtype": 2,
        "matchday": "1",
        "mp": 22,
        "w": 12,
        "d": 3,
        "l": 7,
        "gf": 50,
        "ga": 40,
        "gd": 10,
        "p": 39,
    },
    {
        "team": "CS Rova Mpanjaka",
        "season": 22,
        "matchtype": 2,
        "matchday": "1",
        "mp": 22,
        "w": 12,
        "d": 3,
        "l": 7,
        "gf": 63,
        "ga": 56,
        "gd": 7,
        "p": 39,
    },
    {
        "team": "CD Tenochtitlan",
        "season": 22,
        "matchtype": 1,
        "matchday": "1",
        "mp": 22,
        "w": 11,
        "d": 1,
        "l": 10,
        "gf": 41,
        "ga": 42,
        "gd": -1,
        "p": 34,
    },
    {
        "team": "CA Buenos Aires",
        "season": 22,
        "matchtype": 1,
        "matchday": "1",
        "mp": 22,
        "w": 11,
        "d": 1,
        "l": 10,
        "gf": 50,
        "ga": 55,
        "gd": -5,
        "p": 34,
    },
    {
        "team": "AF Masques Sacrés",
        "season": 22,
        "matchtype": 2,
        "matchday": "2",
        "mp": 22,
        "w": 10,
        "d": 2,
        "l": 10,
        "gf": 54,
        "ga": 44,
        "gd": 10,
        "p": 32,
    },
    {
        "team": "CF Catalunya",
        "season": 22,
        "matchtype": 1,
        "matchday": "2",
        "mp": 22,
        "w": 9,
        "d": 4,
        "l": 9,
        "gf": 40,
        "ga": 43,
        "gd": -3,
        "p": 31,
    },
    {
        "team": "North Shore United",
        "season": 22,
        "matchtype": 2,
        "matchday": "2",
        "mp": 22,
        "w": 9,
        "d": 3,
        "l": 10,
        "gf": 69,
        "ga": 57,
        "gd": 12,
        "p": 30,
    },
    {
        "team": "Xelajú Cósmico FC",
        "season": 22,
        "matchtype": 1,
        "matchday": "2",
        "mp": 22,
        "w": 8,
        "d": 1,
        "l": 13,
        "gf": 43,
        "ga": 56,
        "gd": -13,
        "p": 25,
    },
    {
        "team": "Athênai F.C.",
        "season": 22,
        "matchtype": 2,
        "matchday": "2",
        "mp": 22,
        "w": 6,
        "d": 2,
        "l": 14,
        "gf": 42,
        "ga": 72,
        "gd": -30,
        "p": 20,
    },
    {
        "team": "Shanghai Dragons FC",
        "season": 22,
        "matchtype": 1,
        "matchday": "2",
        "mp": 22,
        "w": 5,
        "d": 4,
        "l": 13,
        "gf": 29,
        "ga": 48,
        "gd": -19,
        "p": 19,
    },
    {
        "team": "A.C. Romana",
        "season": 22,
        "matchtype": 1,
        "matchday": "2",
        "mp": 22,
        "w": 5,
        "d": 2,
        "l": 15,
        "gf": 21,
        "ga": 67,
        "gd": -46,
        "p": 17,
    },
    {
        "team": "Krung Thep FC",
        "season": 22,
        "matchtype": 2,
        "matchday": "2",
        "mp": 22,
        "w": 4,
        "d": 4,
        "l": 14,
        "gf": 58,
        "ga": 70,
        "gd": -12,
        "p": 16,
    },
    {
        "team": "Tokyo S.C.",
        "season": 22,
        "matchtype": 1,
        "matchday": "2",
        "mp": 22,
        "w": 4,
        "d": 3,
        "l": 15,
        "gf": 34,
        "ga": 69,
        "gd": -35,
        "p": 15,
    },
    {
        "team": "Liffeyside Celtic FC",
        "season": 22,
        "matchtype": 1,
        "matchday": "2",
        "mp": 22,
        "w": 1,
        "d": 3,
        "l": 18,
        "gf": 32,
        "ga": 65,
        "gd": -33,
        "p": 6,
    },
    {
        "team": "Cairo City",
        "season": 22,
        "matchtype": 2,
        "matchday": "2",
        "mp": 22,
        "w": 1,
        "d": 2,
        "l": 19,
        "gf": 30,
        "ga": 94,
        "gd": -64,
        "p": 5,
    },
    {
        "team": "Inter London",
        "season": 22,
        "matchtype": 2,
        "matchday": "2",
        "mp": 22,
        "w": 0,
        "d": 1,
        "l": 21,
        "gf": 29,
        "ga": 146,
        "gd": -117,
        "p": 1,
    },
]


